server:
  port: 8080

topicos:
  pagamento:
    request:
      topic: "pagamento.request.topic.v1"

spring:
  kafka:
    bootstrap-servers: >-
      kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9092,
      kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local:9092,
      kafka-controller-2.kafka-controller-headless.kafka.svc.cluster.local:9092
    consumer:
      group-id: pagamento-request-consumer-1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      fetch-max-wait: 500
      fetch-min-size: 1
      max-poll-records: 500
    properties:
      security.protocol: PLAINTEXT
      # Configurações de resiliência
      session.timeout.ms: 45000
      heartbeat.interval.ms: 15000
      max.poll.interval.ms: 300000
      request.timeout.ms: 40000
      # Otimizações para Kubernetes
      reconnect.backoff.ms: 1000
      reconnect.backoff.max.ms: 10000
      metadata.max.age.ms: 30000