apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: kafka-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: producer
        image: kafka-producer:latest
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092